# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.Xil/Vivado-16648-somasai/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xczu3eg-sbva484-1-e
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/avgpool_8x8.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/avgpool_concat.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/avgpool_concat_oucHz.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ti0iy.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ti1iI.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ti2iS.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ti3i2.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ti4jc.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ti5jm.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ti6jw.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ti7jG.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ti8jQ.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ti9j0.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiAem.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tib0s.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tib1s.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tib2s.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tib3s.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tib4t.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tib5t.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tib6t.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tib7t.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tib8t.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tib9t.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibak.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibAo.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibbk.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibBo.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibck.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibCo.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibdk.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibDo.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibek.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibEo.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiBew.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibfk.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibFp.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibgk.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibGp.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibhl.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibHp.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibil.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibIp.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibjl.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibJp.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibkb.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibkl.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibKp.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibll.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibLp.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibml.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibMq.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibnm.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibNq.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibom.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibOq.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibpm.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibPq.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibqm.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibQq.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibrm.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibRq.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibsm.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibSr.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibtn.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibTr.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibun.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibUr.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibvn.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibVr.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibwn.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibWr.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibxn.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibXr.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibyn.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibYs.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibzo.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tibZs.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticau.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticbu.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticcu.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticdu.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiCeG.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticeu.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticfu.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticgu.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tichv.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticiv.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticjv.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tickv.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticlv.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticmv.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticnw.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticow.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticpw.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticqw.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticrw.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticsw.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tictx.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticud.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_ticux.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tidEe.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiDeQ.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiEe0.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tieOg.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiFfa.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tifYi.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tig8j.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiGfk.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tihbi.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiHfu.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiibs.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiIfE.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tijbC.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiJfO.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tikbM.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiKfY.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tilbW.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tile.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiLf8.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_timb6.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiMgi.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tincg.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiNgs.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiocq.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiOgC.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tipcA.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiPgM.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiqcK.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiQgW.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tircU.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiRg6.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tisc4.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiShg.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_titde.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiThq.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiudo.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiUhA.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tivdy.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiVhK.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiwdI.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiWhU.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tixdS.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiXh4.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiyd2.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiYie.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tizec.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/binary_conv3x3_tiZio.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/bn1.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/bn_relu_shortcut.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/compute_engine_64.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_CTRL_s_axi.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_fcmp_32ePU.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_gate_mask.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_IMG_m_axi.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_linear_eOU.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mac_mulcAy.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mac_mulcBy.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mac_mulcEy.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mac_mulcGz.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_msb_fmaddE.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_msb_fmadfE.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mul_mulcCy.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mul_mulcDy.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mul_mulcFz.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mul_mulcxx.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mul_muldaE.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mul_muldbE.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mux_104c9D.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mux_164c8D.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mux_164cXB.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mux_336cvx.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mux_42_cyx.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mux_42_czy.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_mux_647cwx.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_out_bufdgE.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_pool_oudcE.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/FracNet_T_RESULT_m_axi.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/matmul.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/matmul_linear_weic0C.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/matmul_linear_weic1C.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/matmul_linear_weic2C.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/matmul_linear_weic3C.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/matmul_linear_weic4D.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/matmul_linear_weic5D.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/matmul_linear_weic6D.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/matmul_linear_weic7D.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/matmul_linear_weicYC.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/matmul_linear_weicZC.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/quant_and_pack.v
      C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/bnn.prj/solution1/syn/verilog/to2bit.v
    }
      rt::read_vhdl -lib xbip_utils_v3_0_10 c:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.srcs/sources_1/ip/FracNet_T_ap_fcmp_0_no_dsp_32/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_utils_v2_0_6 c:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.srcs/sources_1/ip/FracNet_T_ap_fcmp_0_no_dsp_32/hdl/axi_utils_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0_6 c:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.srcs/sources_1/ip/FracNet_T_ap_fcmp_0_no_dsp_32/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0_4 c:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.srcs/sources_1/ip/FracNet_T_ap_fcmp_0_no_dsp_32/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0_6 c:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.srcs/sources_1/ip/FracNet_T_ap_fcmp_0_no_dsp_32/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_multadd_v3_0_6 c:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.srcs/sources_1/ip/FracNet_T_ap_fcmp_0_no_dsp_32/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_bram18k_v3_0_6 c:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.srcs/sources_1/ip/FracNet_T_ap_fcmp_0_no_dsp_32/hdl/xbip_bram18k_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mult_gen_v12_0_16 c:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.srcs/sources_1/ip/FracNet_T_ap_fcmp_0_no_dsp_32/hdl/mult_gen_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib floating_point_v7_1_9 c:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.srcs/sources_1/ip/FracNet_T_ap_fcmp_0_no_dsp_32/hdl/floating_point_v7_1_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib c:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.srcs/sources_1/ip/FracNet_T_ap_fcmp_0_no_dsp_32/synth/FracNet_T_ap_fcmp_0_no_dsp_32.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top FracNet_T
    rt::set_parameter enableIncremental true
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/gagan/Downloads/FracBNN_with_modes/xcel-cifar10/source/.Xil/Vivado-16648-somasai/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
