// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _to2bit_HH_
#define _to2bit_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct to2bit : public sc_module {
    // Port declarations 4
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<16> > x_V;
    sc_out< sc_lv<2> > ap_return;


    // Module declarations
    to2bit(sc_module_name name);
    SC_HAS_PROCESS(to2bit);

    ~to2bit();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > p_Result_s_fu_84_p3;
    sc_signal< sc_lv<1> > p_Result_s_reg_248;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<2> > temp_V_1_fu_122_p2;
    sc_signal< sc_lv<2> > temp_V_1_reg_254;
    sc_signal< sc_lv<1> > and_ln781_fu_178_p2;
    sc_signal< sc_lv<1> > and_ln781_reg_260;
    sc_signal< sc_lv<1> > or_ln785_fu_184_p2;
    sc_signal< sc_lv<1> > or_ln785_reg_266;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<17> > sext_ln703_fu_48_p1;
    sc_signal< sc_lv<17> > ret_V_fu_52_p2;
    sc_signal< sc_lv<24> > shl_ln1118_1_fu_66_p3;
    sc_signal< sc_lv<26> > shl_ln_fu_58_p3;
    sc_signal< sc_lv<26> > sext_ln1118_fu_74_p1;
    sc_signal< sc_lv<26> > r_V_fu_78_p2;
    sc_signal< sc_lv<1> > tmp_3_fu_110_p3;
    sc_signal< sc_lv<2> > zext_ln415_fu_118_p1;
    sc_signal< sc_lv<2> > temp_V_fu_92_p4;
    sc_signal< sc_lv<1> > tmp_4_fu_128_p3;
    sc_signal< sc_lv<1> > p_Result_1_fu_102_p3;
    sc_signal< sc_lv<1> > xor_ln416_fu_136_p2;
    sc_signal< sc_lv<9> > tmp_fu_148_p4;
    sc_signal< sc_lv<1> > carry_1_fu_142_p2;
    sc_signal< sc_lv<1> > Range1_all_ones_fu_158_p2;
    sc_signal< sc_lv<1> > Range1_all_zeros_fu_164_p2;
    sc_signal< sc_lv<1> > deleted_zeros_fu_170_p3;
    sc_signal< sc_lv<1> > xor_ln781_fu_190_p2;
    sc_signal< sc_lv<1> > xor_ln340_fu_205_p2;
    sc_signal< sc_lv<1> > or_ln340_1_fu_210_p2;
    sc_signal< sc_lv<1> > overflow_fu_200_p2;
    sc_signal< sc_lv<1> > and_ln340_fu_215_p2;
    sc_signal< sc_lv<1> > neg_src_fu_195_p2;
    sc_signal< sc_lv<1> > or_ln340_fu_220_p2;
    sc_signal< sc_lv<2> > select_ln340_fu_226_p3;
    sc_signal< sc_lv<2> > select_ln396_fu_233_p3;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<17> ap_const_lv17_80;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<9> ap_const_lv9_1FF;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_Range1_all_ones_fu_158_p2();
    void thread_Range1_all_zeros_fu_164_p2();
    void thread_and_ln340_fu_215_p2();
    void thread_and_ln781_fu_178_p2();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_return();
    void thread_carry_1_fu_142_p2();
    void thread_deleted_zeros_fu_170_p3();
    void thread_neg_src_fu_195_p2();
    void thread_or_ln340_1_fu_210_p2();
    void thread_or_ln340_fu_220_p2();
    void thread_or_ln785_fu_184_p2();
    void thread_overflow_fu_200_p2();
    void thread_p_Result_1_fu_102_p3();
    void thread_p_Result_s_fu_84_p3();
    void thread_r_V_fu_78_p2();
    void thread_ret_V_fu_52_p2();
    void thread_select_ln340_fu_226_p3();
    void thread_select_ln396_fu_233_p3();
    void thread_sext_ln1118_fu_74_p1();
    void thread_sext_ln703_fu_48_p1();
    void thread_shl_ln1118_1_fu_66_p3();
    void thread_shl_ln_fu_58_p3();
    void thread_temp_V_1_fu_122_p2();
    void thread_temp_V_fu_92_p4();
    void thread_tmp_3_fu_110_p3();
    void thread_tmp_4_fu_128_p3();
    void thread_tmp_fu_148_p4();
    void thread_xor_ln340_fu_205_p2();
    void thread_xor_ln416_fu_136_p2();
    void thread_xor_ln781_fu_190_p2();
    void thread_zext_ln415_fu_118_p1();
};

}

using namespace ap_rtl;

#endif
