// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "to2bit.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const bool to2bit::ap_const_boolean_1 = true;
const bool to2bit::ap_const_boolean_0 = false;
const sc_lv<17> to2bit::ap_const_lv17_80 = "10000000";
const sc_lv<9> to2bit::ap_const_lv9_0 = "000000000";
const sc_lv<7> to2bit::ap_const_lv7_0 = "0000000";
const sc_lv<32> to2bit::ap_const_lv32_19 = "11001";
const sc_lv<32> to2bit::ap_const_lv32_F = "1111";
const sc_lv<32> to2bit::ap_const_lv32_10 = "10000";
const sc_lv<32> to2bit::ap_const_lv32_E = "1110";
const sc_lv<32> to2bit::ap_const_lv32_1 = "1";
const sc_lv<1> to2bit::ap_const_lv1_1 = "1";
const sc_lv<32> to2bit::ap_const_lv32_11 = "10001";
const sc_lv<9> to2bit::ap_const_lv9_1FF = "111111111";
const sc_lv<2> to2bit::ap_const_lv2_3 = "11";
const sc_lv<2> to2bit::ap_const_lv2_0 = "00";
const sc_logic to2bit::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic to2bit::ap_const_logic_0 = sc_dt::Log_0;

to2bit::to2bit(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Range1_all_ones_fu_158_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_fu_148_p4 );

    SC_METHOD(thread_Range1_all_zeros_fu_164_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_fu_148_p4 );

    SC_METHOD(thread_and_ln340_fu_215_p2);
    sensitive << ( or_ln785_reg_266 );
    sensitive << ( or_ln340_1_fu_210_p2 );

    SC_METHOD(thread_and_ln781_fu_178_p2);
    sensitive << ( carry_1_fu_142_p2 );
    sensitive << ( Range1_all_ones_fu_158_p2 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_ln340_fu_220_p2 );
    sensitive << ( select_ln340_fu_226_p3 );
    sensitive << ( select_ln396_fu_233_p3 );

    SC_METHOD(thread_carry_1_fu_142_p2);
    sensitive << ( p_Result_1_fu_102_p3 );
    sensitive << ( xor_ln416_fu_136_p2 );

    SC_METHOD(thread_deleted_zeros_fu_170_p3);
    sensitive << ( carry_1_fu_142_p2 );
    sensitive << ( Range1_all_ones_fu_158_p2 );
    sensitive << ( Range1_all_zeros_fu_164_p2 );

    SC_METHOD(thread_neg_src_fu_195_p2);
    sensitive << ( p_Result_s_reg_248 );
    sensitive << ( xor_ln781_fu_190_p2 );

    SC_METHOD(thread_or_ln340_1_fu_210_p2);
    sensitive << ( and_ln781_reg_260 );
    sensitive << ( xor_ln340_fu_205_p2 );

    SC_METHOD(thread_or_ln340_fu_220_p2);
    sensitive << ( or_ln340_1_fu_210_p2 );
    sensitive << ( overflow_fu_200_p2 );

    SC_METHOD(thread_or_ln785_fu_184_p2);
    sensitive << ( p_Result_s_fu_84_p3 );
    sensitive << ( deleted_zeros_fu_170_p3 );

    SC_METHOD(thread_overflow_fu_200_p2);
    sensitive << ( or_ln785_reg_266 );

    SC_METHOD(thread_p_Result_1_fu_102_p3);
    sensitive << ( r_V_fu_78_p2 );

    SC_METHOD(thread_p_Result_s_fu_84_p3);
    sensitive << ( r_V_fu_78_p2 );

    SC_METHOD(thread_r_V_fu_78_p2);
    sensitive << ( shl_ln_fu_58_p3 );
    sensitive << ( sext_ln1118_fu_74_p1 );

    SC_METHOD(thread_ret_V_fu_52_p2);
    sensitive << ( sext_ln703_fu_48_p1 );

    SC_METHOD(thread_select_ln340_fu_226_p3);
    sensitive << ( temp_V_1_reg_254 );
    sensitive << ( and_ln340_fu_215_p2 );

    SC_METHOD(thread_select_ln396_fu_233_p3);
    sensitive << ( temp_V_1_reg_254 );
    sensitive << ( neg_src_fu_195_p2 );

    SC_METHOD(thread_sext_ln1118_fu_74_p1);
    sensitive << ( shl_ln1118_1_fu_66_p3 );

    SC_METHOD(thread_sext_ln703_fu_48_p1);
    sensitive << ( x_V );

    SC_METHOD(thread_shl_ln1118_1_fu_66_p3);
    sensitive << ( ret_V_fu_52_p2 );

    SC_METHOD(thread_shl_ln_fu_58_p3);
    sensitive << ( ret_V_fu_52_p2 );

    SC_METHOD(thread_temp_V_1_fu_122_p2);
    sensitive << ( zext_ln415_fu_118_p1 );
    sensitive << ( temp_V_fu_92_p4 );

    SC_METHOD(thread_temp_V_fu_92_p4);
    sensitive << ( r_V_fu_78_p2 );

    SC_METHOD(thread_tmp_3_fu_110_p3);
    sensitive << ( r_V_fu_78_p2 );

    SC_METHOD(thread_tmp_4_fu_128_p3);
    sensitive << ( temp_V_1_fu_122_p2 );

    SC_METHOD(thread_tmp_fu_148_p4);
    sensitive << ( r_V_fu_78_p2 );

    SC_METHOD(thread_xor_ln340_fu_205_p2);
    sensitive << ( p_Result_s_reg_248 );

    SC_METHOD(thread_xor_ln416_fu_136_p2);
    sensitive << ( tmp_4_fu_128_p3 );

    SC_METHOD(thread_xor_ln781_fu_190_p2);
    sensitive << ( and_ln781_reg_260 );

    SC_METHOD(thread_zext_ln415_fu_118_p1);
    sensitive << ( tmp_3_fu_110_p3 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "to2bit_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, x_V, "(port)x_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, p_Result_s_fu_84_p3, "p_Result_s_fu_84_p3");
    sc_trace(mVcdFile, p_Result_s_reg_248, "p_Result_s_reg_248");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, temp_V_1_fu_122_p2, "temp_V_1_fu_122_p2");
    sc_trace(mVcdFile, temp_V_1_reg_254, "temp_V_1_reg_254");
    sc_trace(mVcdFile, and_ln781_fu_178_p2, "and_ln781_fu_178_p2");
    sc_trace(mVcdFile, and_ln781_reg_260, "and_ln781_reg_260");
    sc_trace(mVcdFile, or_ln785_fu_184_p2, "or_ln785_fu_184_p2");
    sc_trace(mVcdFile, or_ln785_reg_266, "or_ln785_reg_266");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, sext_ln703_fu_48_p1, "sext_ln703_fu_48_p1");
    sc_trace(mVcdFile, ret_V_fu_52_p2, "ret_V_fu_52_p2");
    sc_trace(mVcdFile, shl_ln1118_1_fu_66_p3, "shl_ln1118_1_fu_66_p3");
    sc_trace(mVcdFile, shl_ln_fu_58_p3, "shl_ln_fu_58_p3");
    sc_trace(mVcdFile, sext_ln1118_fu_74_p1, "sext_ln1118_fu_74_p1");
    sc_trace(mVcdFile, r_V_fu_78_p2, "r_V_fu_78_p2");
    sc_trace(mVcdFile, tmp_3_fu_110_p3, "tmp_3_fu_110_p3");
    sc_trace(mVcdFile, zext_ln415_fu_118_p1, "zext_ln415_fu_118_p1");
    sc_trace(mVcdFile, temp_V_fu_92_p4, "temp_V_fu_92_p4");
    sc_trace(mVcdFile, tmp_4_fu_128_p3, "tmp_4_fu_128_p3");
    sc_trace(mVcdFile, p_Result_1_fu_102_p3, "p_Result_1_fu_102_p3");
    sc_trace(mVcdFile, xor_ln416_fu_136_p2, "xor_ln416_fu_136_p2");
    sc_trace(mVcdFile, tmp_fu_148_p4, "tmp_fu_148_p4");
    sc_trace(mVcdFile, carry_1_fu_142_p2, "carry_1_fu_142_p2");
    sc_trace(mVcdFile, Range1_all_ones_fu_158_p2, "Range1_all_ones_fu_158_p2");
    sc_trace(mVcdFile, Range1_all_zeros_fu_164_p2, "Range1_all_zeros_fu_164_p2");
    sc_trace(mVcdFile, deleted_zeros_fu_170_p3, "deleted_zeros_fu_170_p3");
    sc_trace(mVcdFile, xor_ln781_fu_190_p2, "xor_ln781_fu_190_p2");
    sc_trace(mVcdFile, xor_ln340_fu_205_p2, "xor_ln340_fu_205_p2");
    sc_trace(mVcdFile, or_ln340_1_fu_210_p2, "or_ln340_1_fu_210_p2");
    sc_trace(mVcdFile, overflow_fu_200_p2, "overflow_fu_200_p2");
    sc_trace(mVcdFile, and_ln340_fu_215_p2, "and_ln340_fu_215_p2");
    sc_trace(mVcdFile, neg_src_fu_195_p2, "neg_src_fu_195_p2");
    sc_trace(mVcdFile, or_ln340_fu_220_p2, "or_ln340_fu_220_p2");
    sc_trace(mVcdFile, select_ln340_fu_226_p3, "select_ln340_fu_226_p3");
    sc_trace(mVcdFile, select_ln396_fu_233_p3, "select_ln396_fu_233_p3");
#endif

    }
}

to2bit::~to2bit() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void to2bit::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        and_ln781_reg_260 = and_ln781_fu_178_p2.read();
        or_ln785_reg_266 = or_ln785_fu_184_p2.read();
        p_Result_s_reg_248 = r_V_fu_78_p2.read().range(25, 25);
        temp_V_1_reg_254 = temp_V_1_fu_122_p2.read();
    }
}

void to2bit::thread_Range1_all_ones_fu_158_p2() {
    Range1_all_ones_fu_158_p2 = (!tmp_fu_148_p4.read().is_01() || !ap_const_lv9_1FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_148_p4.read() == ap_const_lv9_1FF);
}

void to2bit::thread_Range1_all_zeros_fu_164_p2() {
    Range1_all_zeros_fu_164_p2 = (!tmp_fu_148_p4.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_148_p4.read() == ap_const_lv9_0);
}

void to2bit::thread_and_ln340_fu_215_p2() {
    and_ln340_fu_215_p2 = (or_ln785_reg_266.read() & or_ln340_1_fu_210_p2.read());
}

void to2bit::thread_and_ln781_fu_178_p2() {
    and_ln781_fu_178_p2 = (carry_1_fu_142_p2.read() & Range1_all_ones_fu_158_p2.read());
}

void to2bit::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void to2bit::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void to2bit::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void to2bit::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void to2bit::thread_ap_return() {
    ap_return = (!or_ln340_fu_220_p2.read()[0].is_01())? sc_lv<2>(): ((or_ln340_fu_220_p2.read()[0].to_bool())? select_ln340_fu_226_p3.read(): select_ln396_fu_233_p3.read());
}

void to2bit::thread_carry_1_fu_142_p2() {
    carry_1_fu_142_p2 = (p_Result_1_fu_102_p3.read() & xor_ln416_fu_136_p2.read());
}

void to2bit::thread_deleted_zeros_fu_170_p3() {
    deleted_zeros_fu_170_p3 = (!carry_1_fu_142_p2.read()[0].is_01())? sc_lv<1>(): ((carry_1_fu_142_p2.read()[0].to_bool())? Range1_all_ones_fu_158_p2.read(): Range1_all_zeros_fu_164_p2.read());
}

void to2bit::thread_neg_src_fu_195_p2() {
    neg_src_fu_195_p2 = (p_Result_s_reg_248.read() & xor_ln781_fu_190_p2.read());
}

void to2bit::thread_or_ln340_1_fu_210_p2() {
    or_ln340_1_fu_210_p2 = (and_ln781_reg_260.read() | xor_ln340_fu_205_p2.read());
}

void to2bit::thread_or_ln340_fu_220_p2() {
    or_ln340_fu_220_p2 = (or_ln340_1_fu_210_p2.read() | overflow_fu_200_p2.read());
}

void to2bit::thread_or_ln785_fu_184_p2() {
    or_ln785_fu_184_p2 = (deleted_zeros_fu_170_p3.read() | p_Result_s_fu_84_p3.read());
}

void to2bit::thread_overflow_fu_200_p2() {
    overflow_fu_200_p2 = (or_ln785_reg_266.read() ^ ap_const_lv1_1);
}

void to2bit::thread_p_Result_1_fu_102_p3() {
    p_Result_1_fu_102_p3 = r_V_fu_78_p2.read().range(16, 16);
}

void to2bit::thread_p_Result_s_fu_84_p3() {
    p_Result_s_fu_84_p3 = r_V_fu_78_p2.read().range(25, 25);
}

void to2bit::thread_r_V_fu_78_p2() {
    r_V_fu_78_p2 = (!shl_ln_fu_58_p3.read().is_01() || !sext_ln1118_fu_74_p1.read().is_01())? sc_lv<26>(): (sc_biguint<26>(shl_ln_fu_58_p3.read()) - sc_bigint<26>(sext_ln1118_fu_74_p1.read()));
}

void to2bit::thread_ret_V_fu_52_p2() {
    ret_V_fu_52_p2 = (!ap_const_lv17_80.is_01() || !sext_ln703_fu_48_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_80) + sc_bigint<17>(sext_ln703_fu_48_p1.read()));
}

void to2bit::thread_select_ln340_fu_226_p3() {
    select_ln340_fu_226_p3 = (!and_ln340_fu_215_p2.read()[0].is_01())? sc_lv<2>(): ((and_ln340_fu_215_p2.read()[0].to_bool())? temp_V_1_reg_254.read(): ap_const_lv2_3);
}

void to2bit::thread_select_ln396_fu_233_p3() {
    select_ln396_fu_233_p3 = (!neg_src_fu_195_p2.read()[0].is_01())? sc_lv<2>(): ((neg_src_fu_195_p2.read()[0].to_bool())? ap_const_lv2_0: temp_V_1_reg_254.read());
}

void to2bit::thread_sext_ln1118_fu_74_p1() {
    sext_ln1118_fu_74_p1 = esl_sext<26,24>(shl_ln1118_1_fu_66_p3.read());
}

void to2bit::thread_sext_ln703_fu_48_p1() {
    sext_ln703_fu_48_p1 = esl_sext<17,16>(x_V.read());
}

void to2bit::thread_shl_ln1118_1_fu_66_p3() {
    shl_ln1118_1_fu_66_p3 = esl_concat<17,7>(ret_V_fu_52_p2.read(), ap_const_lv7_0);
}

void to2bit::thread_shl_ln_fu_58_p3() {
    shl_ln_fu_58_p3 = esl_concat<17,9>(ret_V_fu_52_p2.read(), ap_const_lv9_0);
}

void to2bit::thread_temp_V_1_fu_122_p2() {
    temp_V_1_fu_122_p2 = (!zext_ln415_fu_118_p1.read().is_01() || !temp_V_fu_92_p4.read().is_01())? sc_lv<2>(): (sc_biguint<2>(zext_ln415_fu_118_p1.read()) + sc_biguint<2>(temp_V_fu_92_p4.read()));
}

void to2bit::thread_temp_V_fu_92_p4() {
    temp_V_fu_92_p4 = r_V_fu_78_p2.read().range(16, 15);
}

void to2bit::thread_tmp_3_fu_110_p3() {
    tmp_3_fu_110_p3 = r_V_fu_78_p2.read().range(14, 14);
}

void to2bit::thread_tmp_4_fu_128_p3() {
    tmp_4_fu_128_p3 = temp_V_1_fu_122_p2.read().range(1, 1);
}

void to2bit::thread_tmp_fu_148_p4() {
    tmp_fu_148_p4 = r_V_fu_78_p2.read().range(25, 17);
}

void to2bit::thread_xor_ln340_fu_205_p2() {
    xor_ln340_fu_205_p2 = (p_Result_s_reg_248.read() ^ ap_const_lv1_1);
}

void to2bit::thread_xor_ln416_fu_136_p2() {
    xor_ln416_fu_136_p2 = (tmp_4_fu_128_p3.read() ^ ap_const_lv1_1);
}

void to2bit::thread_xor_ln781_fu_190_p2() {
    xor_ln781_fu_190_p2 = (and_ln781_reg_260.read() ^ ap_const_lv1_1);
}

void to2bit::thread_zext_ln415_fu_118_p1() {
    zext_ln415_fu_118_p1 = esl_zext<2,1>(tmp_3_fu_110_p3.read());
}

}

