-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity to2bit is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x_V : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of to2bit is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv17_80 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal p_Result_s_fu_84_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_reg_248 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal temp_V_1_fu_122_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal temp_V_1_reg_254 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln781_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln781_reg_260 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_fu_184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln785_reg_266 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sext_ln703_fu_48_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ret_V_fu_52_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln1118_1_fu_66_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln_fu_58_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1118_fu_74_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_fu_78_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_3_fu_110_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_fu_118_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal temp_V_fu_92_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_128_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_1_fu_102_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_148_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal carry_1_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_170_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln781_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_fu_205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_1_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln340_fu_215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_fu_195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_fu_226_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln396_fu_233_p3 : STD_LOGIC_VECTOR (1 downto 0);


begin



    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln781_reg_260 <= and_ln781_fu_178_p2;
                or_ln785_reg_266 <= or_ln785_fu_184_p2;
                p_Result_s_reg_248 <= r_V_fu_78_p2(25 downto 25);
                temp_V_1_reg_254 <= temp_V_1_fu_122_p2;
            end if;
        end if;
    end process;
    Range1_all_ones_fu_158_p2 <= "1" when (tmp_fu_148_p4 = ap_const_lv9_1FF) else "0";
    Range1_all_zeros_fu_164_p2 <= "1" when (tmp_fu_148_p4 = ap_const_lv9_0) else "0";
    and_ln340_fu_215_p2 <= (or_ln785_reg_266 and or_ln340_1_fu_210_p2);
    and_ln781_fu_178_p2 <= (carry_1_fu_142_p2 and Range1_all_ones_fu_158_p2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= 
        select_ln340_fu_226_p3 when (or_ln340_fu_220_p2(0) = '1') else 
        select_ln396_fu_233_p3;
    carry_1_fu_142_p2 <= (xor_ln416_fu_136_p2 and p_Result_1_fu_102_p3);
    deleted_zeros_fu_170_p3 <= 
        Range1_all_ones_fu_158_p2 when (carry_1_fu_142_p2(0) = '1') else 
        Range1_all_zeros_fu_164_p2;
    neg_src_fu_195_p2 <= (xor_ln781_fu_190_p2 and p_Result_s_reg_248);
    or_ln340_1_fu_210_p2 <= (xor_ln340_fu_205_p2 or and_ln781_reg_260);
    or_ln340_fu_220_p2 <= (overflow_fu_200_p2 or or_ln340_1_fu_210_p2);
    or_ln785_fu_184_p2 <= (p_Result_s_fu_84_p3 or deleted_zeros_fu_170_p3);
    overflow_fu_200_p2 <= (or_ln785_reg_266 xor ap_const_lv1_1);
    p_Result_1_fu_102_p3 <= r_V_fu_78_p2(16 downto 16);
    p_Result_s_fu_84_p3 <= r_V_fu_78_p2(25 downto 25);
    r_V_fu_78_p2 <= std_logic_vector(unsigned(shl_ln_fu_58_p3) - unsigned(sext_ln1118_fu_74_p1));
    ret_V_fu_52_p2 <= std_logic_vector(unsigned(ap_const_lv17_80) + unsigned(sext_ln703_fu_48_p1));
    select_ln340_fu_226_p3 <= 
        temp_V_1_reg_254 when (and_ln340_fu_215_p2(0) = '1') else 
        ap_const_lv2_3;
    select_ln396_fu_233_p3 <= 
        ap_const_lv2_0 when (neg_src_fu_195_p2(0) = '1') else 
        temp_V_1_reg_254;
        sext_ln1118_fu_74_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1118_1_fu_66_p3),26));

        sext_ln703_fu_48_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_V),17));

    shl_ln1118_1_fu_66_p3 <= (ret_V_fu_52_p2 & ap_const_lv7_0);
    shl_ln_fu_58_p3 <= (ret_V_fu_52_p2 & ap_const_lv9_0);
    temp_V_1_fu_122_p2 <= std_logic_vector(unsigned(zext_ln415_fu_118_p1) + unsigned(temp_V_fu_92_p4));
    temp_V_fu_92_p4 <= r_V_fu_78_p2(16 downto 15);
    tmp_3_fu_110_p3 <= r_V_fu_78_p2(14 downto 14);
    tmp_4_fu_128_p3 <= temp_V_1_fu_122_p2(1 downto 1);
    tmp_fu_148_p4 <= r_V_fu_78_p2(25 downto 17);
    xor_ln340_fu_205_p2 <= (p_Result_s_reg_248 xor ap_const_lv1_1);
    xor_ln416_fu_136_p2 <= (tmp_4_fu_128_p3 xor ap_const_lv1_1);
    xor_ln781_fu_190_p2 <= (ap_const_lv1_1 xor and_ln781_reg_260);
    zext_ln415_fu_118_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_110_p3),2));
end behav;
